# .github/workflows/validate-branch-name.yml
name: Validate Branch Name

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-branch:
    name: Validate Branch Name
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Validate Branch Name
        run: |
          BRANCH_REGEX='^(feature|hotfix|bugfix|release)\/[A-Z]+-[0-9]+.*$'
          if [[ ! "${{ github.head_ref }}" =~ $BRANCH_REGEX ]]; then
            echo "❌ Invalid branch name: '${{ github.head_ref }}'"
            echo "Must match: feature/PROJECT-123-description"
            exit 1
          fi
          echo "✅ Branch name is valid."
