# .github/workflows/validate-pr-title.yml
name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate PR Title
        run: |
          TITLE_REGEX='^(fix|release|feat|hotfix|build|test)\(([A-Z]+-[0-9]+)\):\s.+$'
          if [[ ! "${{ github.event.pull_request.title }}" =~ $TITLE_REGEX ]]; then
            echo "Invalid PR title: '${{ github.event.pull_request.title }}'"
            echo "Must match: type(SCOPE): description"
            echo "Allowed types: fix, release, feat, hotfix, build, test"
            exit 1
          fi
          echo "✅PR title is valid."
